### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by thento123** [johannesboyne/node-stl#15]
Hi, i am a  bit new but i would like to know how am i supposed to import this in an angular project, i tried a lot of different ways but i always get an error. Both import and require did not work for me.

**Comment by lexe11** [comment]
I believe the current implementation only supports Node.js server side use.

**Comment by johannesboyne** [comment]
As written by @lexe11 the current solution is build for Node.js, but one has to say it might be possible to use this in the browser, simply by using http://browserify.org/ and https://www.npmjs.com/package/browserify-fs 

Or you simply copy the code and execute either this line:
https://github.com/johannesboyne/node-stl/blob/master/index.js#L234
or that:
https://github.com/johannesboyne/node-stl/blob/master/index.js#L235
depends whether you have a binary or string representation.
