### ISSUE TITLE
Not working when added with reactjs application

### ISSUE THREAD

**Issue by nandhaFrost02** [johannesboyne/node-stl#21]
Works in the local system(windows)
When uploaded to the cloud function or installed as node_module with react-js application

Am getting the below error
 **TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\...**

**Comment by ForestBeaver** [comment]
This library is for server side Node.js and does not support browsers.

**Comment by johannesboyne** [comment]
Hi @ForestBeaver you probably tried to put in a file-path, but this would try to use the `fs` package of node. You could try the following:

```javascript
const NodeStl = require("node-stl");
const request = require('request');

const requestSettings = {
   method: 'GET',
   url: 'https://s3.amazonaws.com/minifactory-stl/WALLY_1plate.stl',
   encoding: null,
};

request(requestSettings, function(error, response, body) {
    var stl = new NodeStl(body);
    assert.equal(stl.volume, 21.87511539650792);
    done(null);
});
```
