### ISSUE TITLE
Cannot read property 'forEach' of null

### ISSUE THREAD

**Issue by grmmph** [johannesboyne/node-stl#23]
Some stls have no vertexes (as parsed on _parseSTLString())

<img width="1108" alt="Screen Shot 2020-06-14 at 17 20 14" src="https://user-images.githubusercontent.com/5146230/84595938-6fdd7080-ae63-11ea-826c-b4d79400325f.png">

**Comment by johannesboyne** [comment]
Hi @grmmph could you please provide a bit more context, e.g. a sample file to reproduce it.

**Comment by grmmph** [comment]
Here you go
[box.stl.zip](https://github.com/johannesboyne/node-stl/files/4778815/box.stl.zip)

**Comment by grmmph** [comment]
From further investigation it looks like `isBinary` returns `false` for some binary buffers

**Comment by grmmph** [comment]
https://github.com/johannesboyne/node-stl/pull/24

**Comment by johannesboyne** [comment]
Hi @grmmph ,
With a little twist to the code you proposed it worked, I added the box.stl to the test-set for future development. Thanks!
