### ISSUE TITLE
Calculate gram

### ISSUE THREAD

**Issue by 3nd0y** [johannesboyne/node-stl#3]
Hi there,

i just confuse when i got the value in gram, is it for ABS or PLA? 
Also i think this calculation didn't mention if we use support to bed and adhesion right?

**Comment by redwildfire13** [comment]
Weight is volume * density of material. 

It looks like the calculation is using a density of 1.04.

PLA has a density of 1.25 g/cm^3.
ABS has a density of 1.06 g/cm^3.

**Comment by johannesboyne** [comment]
@redwildfire13 & @3nd0y feel free to create a pull request if you prefer a change or add options to the density calculation.

**Comment by lexe11** [comment]
Can we close these old issues?

**Comment by johannesboyne** [comment]
Hi @lexe11 could you please elaborate why? I can imagine, that someone would actually be interested in such a change and would take it as a contribution possibility.

**Comment by lexe11** [comment]
My mistake, I thought we had already implemented this but I see the suggestion is for user defined density. I’ll try to knock this out.

**Comment by lexe11** [comment]
I've submitted a merge request for these changes.
